// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// applyFunc is an autogenerated mock type for the applyFunc type
type applyFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: r
func (_m *applyFunc) Execute(r *http.Request) {
	_m.Called(r)
}

type mockConstructorTestingTnewApplyFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newApplyFunc creates a new instance of applyFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newApplyFunc(t mockConstructorTestingTnewApplyFunc) *applyFunc {
	mock := &applyFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
